# Generated by Django 4.2.18 on 2025-01-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emaiil_token',
            new_name='email_token',
        ),
    ]
