# Generated by Django 4.2.18 on 2025-02-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Coupon_code',
            new_name='coupon_code',
        ),
    ]
